### ISSUE TITLE
Discovery: e-commerce options

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ccxcon#13]

**Comment by justinabrahms** [comment]
Using something like django-oscar isn't feasible, given that we are exposing a REST API. Many of the django project things assume that you'll also be using templates and communicating over http & multipart form data, rather than json payloads.  As such, I'd recommend not using django-oscar (or similar offerings). We could theoretically fork django-oscar, replacing all of its views with json views. Or perhaps having our own views that call deeply into the internals of django-oscar. I think this will be a pretty rough maintenance headache.

The next option is that we write something ourselves. There are tools like [Satchless](http://satchless.com/) which provide some very basic primitives, but this would require us to write our own session/cart handling code, order persistence, payment gateway integration, tax calculation, etc. This is a great deal of work, and I'd suspect we'd miss our February deadline on it.

The last option is that we use a third-party saas tool. I came across [moltin](https://moltin.com/) which I like. It provides an API for us to create listings (when the instructor publishes their course), take payments, and (through the use of webhooks) create the instance on edx when the user pays. The seem to have a very nice [javascript API](https://moltin.com/getting-started/js) that we could use.

I'd like to move forward with the assumption that we use moltin instead of implementing our own ecommerce platform. There are [costs](https://moltin.com/pricing) involved, so if I could get signoff.. I'd appreciate it.

cc @Ferdi 

cc @jamiefolsom and @noisecapella as they'll be working with that API client.

**Comment by pdpinch** [comment]
Interesting. I was assuming that edX was going with REST-based interfaces. But perhaps its the other apps in the stack that are offering REST and Oscar/otto is just a client?

Can you take a look at https://github.com/edx/ecommerce https://github.com/edx/ecommerce just to confirm that they're sticking to templates?

**Comment by Ferdi** [comment]
I was also under the impression that edx was doing REST.  

To add another option to your list: Build a REST interface extension to django oscar.

**Comment by justinabrahms** [comment]
They have an asset pipeline with scss, openid connect, it uses django-oscar (which doesn't expose a rest api), and it's on a separate subdomain. This appears to be a full django web application, not a rest api.

@Ferdi that is option 1, which would involve calling into private APIs of django-oscar. Given that there isn't a backwards compatibility guarantee on django-oscar, keeping up to date with upgrades seems like it would be a bit of a maintenance headache. 

We could possibly work with upstream to see if that's a thing they want and will maintain. Or we could have a fork we don't care to keep up to date.. but that has security implications [made worse because this deals with money]. We could possibly change the default serialization of web requests to `application/json` and redo every template to be a json payload.. but I don't expect that will be particularly easy.

**Comment by Ferdi** [comment]
I agree.  There must be some stable public api in django-oscar , no?  edx has build quite a lot on top of it. 

https://github.com/edx/ecommerce/tree/master/ecommerce

and they have some REST going on there 

https://github.com/edx/ecommerce/blob/master/requirements/base.txt

**Comment by justinabrahms** [comment]
django-oscar has no public API that I'm aware of, only implementation details of their views and models.

They've made backwards incompatible changes in a [minor release](http://django-oscar.readthedocs.org/en/latest/releases/v1.1.html#backwards-incompatible-changes-in-1-1) [more than once.](http://django-oscar.readthedocs.org/en/latest/releases/v1.2.html?highlight=compat#backwards-incompatible-changes-in-oscar-1-2)

edx has built their [own rest API](https://github.com/edx/ecommerce/blob/master/ecommerce/extensions/api/v2/views/baskets.py) on top of django-oscar.

If that's what you want, we can do that too. My preference would be to use moltin, because engineering time is expensive and I think this is the best way forward on the axis of speed, likelihood of not having bugs, and JS integration. I'm not sure of the tolerance MIT has for paying for services, but their prices seem fair.

For reference, it looks like edx has put [10 months of work](https://github.com/edx/ecommerce/graphs/contributors) in with 2 full time engineers on the repo, which isn't launched yet.

**Comment by justinabrahms** [comment]
Another possibility might be a wholesale fork of edx/ecommerce.

On Tuesday, November 17, 2015, Ferdi Alimadhi notifications@github.com
wrote:

> I agree. There must be some stable public api in django-oscar , no? edx
> has build quite a lot on top of it.
> 
> https://github.com/edx/ecommerce/tree/master/ecommerce
> 
> and they have some REST going on there
> 
> https://github.com/edx/ecommerce/blob/master/requirements/base.txt
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mitodl/ccxcon/issues/13#issuecomment-157519465.

## 

Sent via mobile phone.

**Comment by justinabrahms** [comment]
As it stands, we're going to use django-oscar + django-oscar-api inside the teacher's portal codebase, because that's where the users live. 

https://docs.google.com/document/d/1CiCaX9FnpMPTWD-dWS-dBJWYqv4QLEF-pm-l1IOM06E/edit?usp=sharing
