### ISSUE TITLE
protect against overwritten defaults

### ISSUE THREAD

**Issue by justinabrahms** [mitodl/ccxcon#50]
CCXCon has descriptions for courses. This comes from edX.
Users can update these descriptions.
If the user publishes their course again, it will overwrite.

How do we want to fix this? Maybe store updated descriptions in teacher's portal?

**Comment by bdero** [comment]
Maybe there can be an overrides model for course descriptions that exists separately from the initial descriptions altogether. If a course description override exists for course, it's displayed instead of the actual course description.

The course description is owned by edX, and the course description override is owned by either CCXCon or Teacher's Portal.

Let me know if I seem to have missed the mark on what the problem is.

**Comment by noisecapella** [comment]
If the description should be updated at edX too then we should propagate the update that way. If that description won't ever go to edX it seems like the teacher's portal is a good place for it. That way CCXCon is always basically a cache of edX

**Comment by pdpinch** [comment]
modified descriptions in the Teachers Portal should not propagate back to edX. 

I agree that the simplest option would be to store the TP-local changes in the TP, and keep CCXcon in sync with edX. I like to to think of it as a cache/aggregator of multiple edX instances.

**Comment by justinabrahms** [comment]
This is done. TP stores the descriptions. There are no updates in CCXConn aside from edx.
